services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8080
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - objectstorage
    environment:
      - Persistence__ConnectionString=Host=db;Database=ExpenseTracker;Username=postgres;Password=postgres
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ExpenseTracker
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  objectstorage:
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: ADMIN
      MINIO_ROOT_PASSWORD: 5RgTi86oxB2y
    volumes:
      - /minio_data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"