@host = http://localhost:5162

POST {{host}}/api/v1/user/register
Accept: application/json
Content-Type: application/json

{
    "Email": "pippo@mm.it",
    "Password": "Pluto_35"
}

###

POST {{host}}/api/v1/user/login
Accept: application/json
Content-Type: application/json

{
    "Email": "pippo@mm.it",
    "Password": "Pluto_35"
}

###

GET {{host}}/api/v1/user/test
Accept: application/json
Authorization: Bearer eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwidHlwIjoiSldUIiwiY3R5IjoiSldUIn0.KIpNvaf4SElUfql27fzYkZxfbXeUztwdoMNy9X7ch1pCq3eK6E50-BOdeO08fhoaA447PvkFBkuLOZ0OLof1B8gd4u47v6Wz.HC3eonpOf_MW6qHldrSyWQ.1R5MegP2wWKbiKRcdtwM-naqrAm4_3quc9KxJ0PYeUXrPVyBrZSMXAiCotUKjYXsfds1OH4tOoocmc0bR8nk2ktkiNRQEkV-gGLO-E6_BpZT9peNShK5ZLjWz2913E-0MXqXPnufFeJoSiwRnkQZvhX-wVUl-LUGm4EzN_I4KPFTpZuZtEGlxeBOD1osWx3aoBMauolEr1bCMVHMNSFNj7sKaeZTA1qIRJGb3Y3bf8-Wi9fgFxnXse2ncHsY9Vv3NbM7sZZsE1SNgZdrhnAy1kMYdJZ7L2UMz3CbSyfQuVGzIAi0vD01xifdbqW3SMbwuURqQgfGfW8KAqE7AaCeywd5lDGdk5cnRX-UcmLDdRRPvHKMma2pbGSypZxM5DupV1AL0xJLSFTRQgP3GXHMKYoYyLX1ltKqlw02KaOG9bs.ROkx3li_KGR2cTsaNBQ4OUXxgFruP1iOiwyFuTSHhXA