POST {{host}}/api/v1/user/register
Accept: application/json
Content-Type: application/json

{
    "Email": "pippo@mm.it",
    "Password": "Pluto_35"
}

###

POST {{host}}/api/v1/user/login
Accept: application/json
Content-Type: application/json

{
    "Email": "pippo@mm.it",
    "Password": "Pluto_35"
}

###

PUT {{host}}/api/v1/categories
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "RootCategories": [
        {
            "Name": "Home",
            "Childrens": [
                {
                    "Name": "Groceries"
                },
                {
                    "Name": "Bill",
                    "Childrens": [
                        {
                            "Name": "Electricity"
                        },
                        {
                            "Name": "Gas"
                        }
                    ]
                }
            ]
        }
    ]
}

###

GET {{host}}/api/v1/categories
Accept: application/json
Authorization: Bearer {{token}}